# Generated by Django 6.0.6 on 2026-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Producto"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio (S/.)"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="Stock Disponible")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("ELECTRONICA", "Electrónica"),
                            ("ROPA", "Ropa y Calzado"),
                            ("HOGAR", "Hogar y Cocina"),
                            ("LIBROS", "Libros y Papelería"),
                            ("OTROS", "Otros"),
                        ],
                        default="OTROS",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "disponible",
                    models.BooleanField(
                        default=True, verbose_name="¿Está disponible para la venta?"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
